version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: football-league-frontend
    ports:
      - "8081:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:8080/api