version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: football-league-app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    networks:
      - football-league-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: football-league-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - football-league-network

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: football-league-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: football_league
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - football-league-db-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - football-league-network

networks:
  football-league-network:
    driver: bridge

volumes:
  football-league-db-data: